[project]
name = "simpleMDMpy"
description = "python lib for simpleMDM API"
version = "3.0.7"
authors = [
    { name = "SteveKueng", email = "steve.kueng@srgssr.ch" }
]
dependencies = [
    "requests"
]

